-- MySQL Script generated by MySQL Workbench
-- Sat Apr  2 22:22:01 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_filepath` VARCHAR(45) NOT NULL,
  `image_user_fk` INT NOT NULL,
  PRIMARY KEY (`image_id`),
  INDEX `image_user_id_idx` (`image_user_fk` ASC),
  UNIQUE INDEX `image_filepath_UNIQUE` (`image_filepath` ASC),
  CONSTRAINT `image_user_id`
    FOREIGN KEY (`image_user_fk`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_image_fk` INT NOT NULL,
  `comment_user_fk` INT NOT NULL,
  `comment_text` LONGTEXT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `comment_user_id_idx` (`comment_user_fk` ASC),
  INDEX `comment_image_id_idx` (`comment_image_fk` ASC),
  CONSTRAINT `comment_user_id`
    FOREIGN KEY (`comment_user_fk`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_image_id`
    FOREIGN KEY (`comment_image_fk`)
    REFERENCES `mydb`.`Image` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
